dd_bot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Velocity controllers
    right_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: right_wheel_joint
        pid: {p: 0.01, i: 0.01, d: 0}

    left_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: left_wheel_joint
        pid: {p: 0.01, i: 0.01, d: 0}
